"""empty message

Revision ID: af4294e3fa72
Revises: 
Create Date: 2023-11-08 22:43:20.877986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4294e3fa72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invRoles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invStatusProyecto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcionStatus', sa.String(length=100), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invProyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('StatusProyectoId', sa.Integer(), nullable=False),
    sa.Column('proyecto', sa.Text(), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.Column('IDEvento', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['StatusProyectoId'], ['invStatusProyecto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('IDEvento')
    )
    op.create_table('invUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=45), nullable=True),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('apellidoPaterno', sa.String(length=45), nullable=True),
    sa.Column('apellidoMaterno', sa.String(length=45), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('event', sa.String(length=100), nullable=True),
    sa.Column('rolId', sa.Integer(), nullable=False),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rolId'], ['invRoles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invBitacora',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proyectId', sa.Integer(), nullable=False),
    sa.Column('usuarioId', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fechaInicio', sa.DateTime(), nullable=True),
    sa.Column('fechaFin', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.Column('IDEvento', sa.String(length=100), nullable=True),
    sa.Column('isVentana', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proyectId'], ['invProyectos.id'], ),
    sa.ForeignKeyConstraint(['usuarioId'], ['invUsers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invEventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IDEvento', sa.String(length=100), nullable=True),
    sa.Column('AliasEvento', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.Column('ProyectoId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ProyectoId'], ['invProyectos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('IDEvento')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invEventos')
    op.drop_table('invBitacora')
    op.drop_table('invUsers')
    op.drop_table('invProyectos')
    op.drop_table('invStatusProyecto')
    op.drop_table('invRoles')
    # ### end Alembic commands ###
