"""empty message

Revision ID: f97bccd60445
Revises: af45d8b6e2d9
Create Date: 2023-11-15 12:16:41.263872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f97bccd60445'
down_revision = 'af45d8b6e2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invPersonajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('personaje', sa.String(length=45), nullable=True),
    sa.Column('fechaAlta', sa.DateTime(), nullable=True),
    sa.Column('fechaUltimaModificacion', sa.DateTime(), nullable=True),
    sa.Column('comentarioId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentarioId'], ['invBitacora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invPersonajes')
    # ### end Alembic commands ###
